version: 2
project_name: check-aws-cloudwatch-logs-insights
env:
  - GO111MODULE=on
builds:
  - binary: check-aws-cloudwatch-logs-insights
    goarch:
      - amd64
      - arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    formats:
      - zip
    wrap_in_directory: true
release:
  prerelease: auto
