---
name: test

on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  lint:
    uses: mackerelio/workflows/.github/workflows/go-lint.yml@7653987676cc233af59a390d142b5cf6e65a526f # v1.6.0
  test:
    uses: mackerelio/workflows/.github/workflows/go-test.yml@7653987676cc233af59a390d142b5cf6e65a526f # v1.6.0
